### ISSUE TITLE
N^2 behavior when mapping refreshable

### ISSUE THREAD

**Issue by mharris-mharris** [palantir/refreshable#125]
## What happened?

We've had a couple instances where we've called Refreshable.map() in a tight loop and it's caused serious problems.  The main issues here are:

* map() is a really innocuous sounding name.  I map things all the time, why should I be worried about this?
* map() is synchronized, creating a potential bottleneck
* map() copies and for-each's on a data structure every fixed number of invocations.  This data structure is also added to on each map(), so the runtime of this is N^2
* N^2 plus mutex equals walking off a cliff very easily

## What did you want to happen?

3 possible improvements:

1. delete/deprecate the map() function and direct people to just use subscribe or turn the refreshable into a supplier, or rename the map() function to indicate its heftiness
2. Amortize the N^2 behavior down to linear or move it to be asynchronous somehow
3. Use less heavy-weight concurrency than synchronized/mutex (some form of read-write or non-blocking concurrency)

**Comment by carterkozak** [comment]
This project could use some love in the readme and javadoc departments. I recall several discussions when we open-sourced the library about the risk that folks accidentally use Refreshable to implement functional-style programming when it's meant to be used for lower scale configuration updates.

Given the issues we've encountered, I'm not confident renaming methods will encourage developers to do the right things, and in some cases it may result in memory leaks/crashes rather than slowness. I'd prefer to make it performant by default if the risks are minimal to do so, but in any case it's not a good idea to add subscriptions to refreshable objects unnecessarily if subsequent changes aren't needed. Most projects create all refreshable objects in their server initializer block and don't run into this class of issues. We've considered adding static analysis checks to recommend against passing refreshables into constructors, but I'm worried that would have a high false positive rate, and ultimately get ignored too many places to be helpful.

It's also worth noting that the primary performance bottleneck in this case is garbage collection -- if we map in a tight loop we create a lot of objects with links to a parent refreshable in order to receive future updates. In tight loops, those objects tend not to live very long and can be freed quickly. Until that occurs, they must be tracked and updated, but in these cases they're largely unnecessary because they don't last long enough to be updated and could operate on a snapshot.
The iteration within `map` is a fix for an OOM in which updates were very infrequent, and `map` calls were able to build up garbage that wasn't freed. We don't want to make this fast in a way that just allows us to oom quickly, or shift from lock contention to GC pressure!

## N<sup>2</sup>

> map() copies and for-each's on a data structure every fixed number of invocations. This data structure is also added to on each map(), so the runtime of this is N^2

I'm not confident this is in fact N<sup>2</sup>. I would consider it O(N) where N is the number of active subscriptions, but my analysis could very well be incorrect.

> map() copies

Copying the subscribers (size N) is `O(N)`

> and for-each's 

This is for-each element in the copy of our data-structure, also `O(N)`

> on a data structure every fixed number of invocations.
> This data structure is also added to on each map()

This is the number of subscribers, N, however values are also removed every fixed number of iterations as well. In the case of a `map` invocation the list is drained when the refreshable.map resulting Refreshable is freed.

## Alternatives

> direct people to just use subscribe

Please do not use subscribe instead of map, if you don't unsubscribe, you'll have a memory leak! the `map` function helpfully unsubscribes when the resulting refreshable is freed, however subscribe must hold a strong reference to the target consumer, and requires `Disposable::dispose` to be called eventually.

> Amortize the N^2 behavior down to linear or move it to be asynchronous somehow

I'm planning to improve the map `O(N)` behavior when we can leverage java 11 features. The downside of relying on cleaner (basically async cleanup, runs when objects are GCd rather than the first refreshable interaction after) is that it's still possible to call map on more threads than you have running the disposers, so it's possible to OOM in ways that currently provide backpressure via blocking on locks.

> Use less heavy-weight concurrency

There's a branch from a year or so ago which implements [DefaultRefreshable using read/write locks](https://github.com/palantir/refreshable/compare/develop...ckozak/read_write_lock), however there's some risk and I've been holding off to reinvestigate it once cleaners are available.

**Comment by mharris-mharris** [comment]
Thanks for the really detailed update on this Carter.  Sounds like we have some good things coming down the pipeline with Java 11+ and some other work you have on the backburner which sounds great.  Re: O(N^2), if you do O(N) refreshable.maps, the data structure will grow linearly and at fixed intervals perform an O(N) cleanup, making the overall runtime O(N^2).  Sounds like this may be fixed with the async cleanup you referenced, so that's great.

**Comment by carterkozak** [comment]
#130 should be sufficient. We're planning to bump the minimum java requirement for libraries to 11 on April 1st.
